// Row shapes and enums for the tiny-home CRM.
//
// Conventions carried through the whole CRM (deviating from them causes real
// bugs, so they are listed once here):
//
//   * ids are TEXT uuids generated by the app (`newId()` in ./db)
//   * money is INTEGER cents, never floats and never dollars — `fmtMoney` in
//     ./format is the only place that divides by 100
//   * rates are basis points (3700 = 37.00%), so no float drift in the DB
//   * timestamps are ISO-8601 TEXT in UTC; plain dates are 'YYYY-MM-DD' TEXT
//   * every enum below mirrors a SQL CHECK constraint in ./schema — adding a
//     value means editing BOTH plus the label map at the bottom of this file

/* -------------------------------------------------------------------------- */
/* Enums — mirrored by CHECK constraints in ./schema.ts                        */
/* -------------------------------------------------------------------------- */

export const CLIENT_STATUSES = [
  "prospect",
  "qualified",
  "proposal_sent",
  "contracted",
  "owner",
  "dormant",
  "lost",
] as const;
export type ClientStatus = (typeof CLIENT_STATUSES)[number];

export const HEALTHS = ["green", "amber", "red"] as const;
export type Health = (typeof HEALTHS)[number];

export const ENTITY_TYPES = [
  "individual",
  "joint",
  "llc",
  "s_corp",
  "c_corp",
  "partnership",
  "trust",
] as const;
export type EntityType = (typeof ENTITY_TYPES)[number];

export const LEAD_SOURCES = [
  "referral",
  "inbound",
  "outbound",
  "event",
  "cpa_referral",
  "advisor",
  "partner",
  "other",
] as const;
export type LeadSource = (typeof LEAD_SOURCES)[number];

export const CONTACT_ROLES = [
  "principal",
  "spouse",
  "cpa",
  "attorney",
  "wealth_advisor",
  "assistant",
  "other",
] as const;
export type ContactRole = (typeof CONTACT_ROLES)[number];

export const PROPOSAL_STATUSES = ["draft", "sent", "accepted", "declined", "expired"] as const;
export type ProposalStatus = (typeof PROPOSAL_STATUSES)[number];

/**
 * The first three are the generated execution set (see ./contract-templates and
 * docs/). They are produced together and share a `deal_group_id`; the rest are
 * for contracts recorded by hand.
 */
export const CONTRACT_TYPES = [
  "equipment_purchase",
  "equipment_finance",
  "management",
  "unit_purchase",
  "land_purchase",
  "investment",
  "lease",
  "joint_venture",
] as const;
export type ContractType = (typeof CONTRACT_TYPES)[number];

/** The set generated as one deal, in the order they are executed. */
export const GENERATED_CONTRACT_TYPES = [
  "equipment_purchase",
  "equipment_finance",
  "management",
] as const satisfies readonly ContractType[];

export const CONTRACT_STATUSES = [
  "draft",
  "out_for_signature",
  "signed",
  "active",
  "completed",
  "terminated",
] as const;
export type ContractStatus = (typeof CONTRACT_STATUSES)[number];

/**
 * Land parcels the client owns or is pursuing.
 *
 * LEGACY. The business changed: BTB owns the land and the client buys only the
 * home, which sits on a pad BTB provides (see the Management Agreement in
 * docs/, which places the unit "on vacant improved land" the Agent manages).
 * BTB's own land lives in `crm_parks` / `crm_pads` instead — deliberately NOT
 * here, because this table's `client_id` cascades on delete and removing a
 * client would take BTB's land with it.
 */
export const PROPERTY_STATUSES = [
  "prospect",
  "under_contract",
  "owned",
  "listed",
  "sold",
] as const;
export type PropertyStatus = (typeof PROPERTY_STATUSES)[number];

/** A parcel of land BTB owns or is pursuing, on which pads are built. */
export const PARK_STATUSES = [
  "prospect",
  "under_contract",
  "owned",
  "developing",
  "operating",
  "sold",
] as const;
export type ParkStatus = (typeof PARK_STATUSES)[number];

/**
 * One numbered site within a park.
 *
 * `available` and `occupied` are what capacity is counted from: a park's
 * remaining capacity is its available pads, and a client's footprint is the
 * square footage of the pad their home sits on.
 */
export const PAD_STATUSES = [
  "planned",
  "building",
  "available",
  "reserved",
  "occupied",
  "out_of_service",
] as const;
export type PadStatus = (typeof PAD_STATUSES)[number];

/** How a pad's home came to exist — the prefab vs build-on-site question. */
export const BUILD_METHODS = ["prefab", "site_built"] as const;
export type BuildMethod = (typeof BUILD_METHODS)[number];

/** A tiny home, from order through disposal. */
export const UNIT_STATUSES = [
  "planned",
  "ordered",
  "in_production",
  "delivered",
  "installed",
  "in_service",
  "sold",
  "retired",
] as const;
export type UnitStatus = (typeof UNIT_STATUSES)[number];

/**
 * How the unit is used. This is the single most consequential field for the tax
 * case: only business/rental use supports a depreciation deduction, so
 * `personal` zeroes the write-off in ./economics rather than quietly inflating it.
 */
/**
 * How a unit is used — and the difference between the first two decides
 * whether the deal works at all.
 *
 * `transient_rental` is the ONLY one the structure in docs/ is sold on: it
 * clears the §50(b)(2) lodging exclusion through the transient exception at
 * rentals normally UNDER 30 DAYS (Reg. 1.48-1(h)(2)(ii)). It was called
 * `short_term_rental`, which is a different and dangerous idea — "short-term
 * rental" is the familiar §469 SEVEN-day route to non-passive treatment
 * through the taxpayer's own hours, which this structure explicitly does not
 * use, because participation comes from the trustee instead. Two names for two
 * tests invites picking the wrong one, so there is one name and it is the
 * accurate one. See CLAUDE.md, "The two day-counts are different tests".
 */
export const UNIT_USES = ["transient_rental", "long_term_rental", "farm_ag", "commercial", "personal"] as const;
export type UnitUse = (typeof UNIT_USES)[number];

export const TX_KINDS = ["income", "expense"] as const;
export type TxKind = (typeof TX_KINDS)[number];

export const TX_CATEGORIES = [
  "investment",
  "deposit",
  "land_purchase",
  "unit_purchase",
  "site_work",
  "permits",
  "transport",
  "closing_costs",
  "rent",
  "management_fee",
  "insurance",
  "property_tax",
  "maintenance",
  "utilities",
  "professional_fees",
  "distribution",
  "other",
] as const;
export type TxCategory = (typeof TX_CATEGORIES)[number];

export const TX_STATUSES = ["draft", "invoiced", "paid", "overdue", "void"] as const;
export type TxStatus = (typeof TX_STATUSES)[number];

/** Where a shortlisted parcel stands for this client. */
export const SAVED_PARCEL_STATUSES = [
  "shortlisted",
  "owner_contacted",
  "offer_made",
  "under_contract",
  "acquired",
  "rejected",
] as const;
export type SavedParcelStatus = (typeof SAVED_PARCEL_STATUSES)[number];

/**
 * Columns on the shared kanban board, in board order.
 *
 * Three, not five. A board the whole office shares is only useful if a card's
 * column is obvious at a glance to someone who did not move it; every extra
 * column is another judgement call about where something belongs.
 */
export const TODO_STATUSES = ["todo", "doing", "done"] as const;
export type TodoStatus = (typeof TODO_STATUSES)[number];

/**
 * What a conversation is about. `global` is the whole workspace — the assistant
 * opened on a list page, where the question is "which contracts are unsigned",
 * not "how is this account doing". The rest are one record.
 *
 * There is no CHECK on `crm_conversations.scope_type`, so widening this is a
 * code change only; an older row keeps whatever it was written with.
 */
export const AI_SCOPES = ["global", "client", "proposal", "contract"] as const;
export type AiScope = (typeof AI_SCOPES)[number];

/* -------------------------------------------------------------------------- */
/* Rows                                                                        */
/* -------------------------------------------------------------------------- */

export interface CrmClient {
  id: string;
  name: string;
  legal_name: string | null;
  status: ClientStatus;
  health: Health;
  source: LeadSource;
  entity_type: EntityType;

  email: string | null;
  phone: string | null;
  city: string | null;
  state: string | null;

  /** Tax profile — drives every figure in ./economics. */
  tax_state: string | null;
  /** Marginal federal+state rate in basis points (3700 = 37%). */
  marginal_rate_bps: number | null;
  est_annual_income_cents: number | null;
  target_writeoff_cents: number | null;
  investment_capacity_cents: number | null;
  cpa_name: string | null;
  cpa_email: string | null;

  /** Land criteria — pre-fills the per-client parcel search. */
  target_state: string | null;
  target_county: string | null;
  target_min_acres: number | null;
  target_max_acres: number | null;
  target_max_price_cents: number | null;

  owner_email: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmContact {
  id: string;
  client_id: string;
  name: string;
  role: ContactRole;
  title: string | null;
  email: string | null;
  phone: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmProposal {
  id: string;
  client_id: string;
  title: string;
  status: ProposalStatus;

  /** Frozen inputs — what was quoted, kept verbatim so the doc never drifts. */
  unit_count: number;
  unit_cost_cents: number;
  site_work_cents: number;
  soft_costs_cents: number;
  land_cost_cents: number;
  /** Cash deposit; the balance is seller-financed. Zero means an all-cash deal. */
  down_payment_cents: number;
  marginal_rate_bps: number;
  bonus_rate_bps: number;
  useful_life_years: number;
  monthly_rent_cents: number;
  occupancy_bps: number;
  opex_bps: number;

  /** Frozen outputs — computed in code, never by the model. */
  total_investment_cents: number;
  depreciable_basis_cents: number;
  year_one_deduction_cents: number;
  year_one_tax_savings_cents: number;
  /** Cash out of pocket less the tax benefit. NEGATIVE means ahead in year one. */
  net_year_one_outlay_cents: number;
  financed_cents: number;
  monthly_note_cents: number;
  annual_debt_service_cents: number;
  cash_invested_cents: number;
  /** Deduction per dollar of cash, in bps. 100000 is "10 to 1". */
  deduction_leverage_bps: number | null;
  annual_noi_cents: number;
  annual_cash_flow_cents: number;
  cash_on_cash_bps: number | null;
  payback_years: number | null;

  body_md: string;
  valid_until: string | null;
  created_by: string | null;
  sent_at: string | null;

  /**
   * Withdrawn, not deleted. Deliberately NOT a status value — see ./archive.ts.
   * Optional here because most callers never select it; the column always exists.
   */
  archived_at?: string | null;
  archived_by?: string | null;

  created_at: string;
  updated_at: string;
}

export interface CrmContract {
  id: string;
  client_id: string;
  proposal_id: string | null;
  title: string;
  type: ContractType;
  status: ContractStatus;
  value_cents: number;
  counterparty: string | null;
  document_url: string | null;
  effective_date: string | null;
  end_date: string | null;
  signed_at: string | null;
  notes: string | null;

  /**
   * Set only on the generated execution set. The deal terms are frozen here the
   * same way proposal economics are frozen — a signed document must keep saying
   * what it said. They are NOT patchable; regenerate instead.
   */
  deal_group_id: string | null;
  purchase_price_cents: number | null;
  down_payment_cents: number | null;
  financed_cents: number | null;
  note_rate_bps: number | null;
  note_term_months: number | null;
  monthly_payment_cents: number | null;
  revenue_split_bps: number | null;
  buyer_legal_name: string | null;
  trust_name: string | null;
  unit_vin: string | null;
  collateral_location: string | null;
  body_md: string | null;
  generated_at: string | null;

  /** As on CrmProposal — archived, never deleted. See ./archive.ts. */
  archived_at?: string | null;
  archived_by?: string | null;

  created_at: string;
  updated_at: string;
  /** True when generated before the seller/wire block was configured. */
  not_for_execution?: boolean;
  /** What was unset at generation time, for the banner. */
  config_issues?: string | null;
}

/** A land holding. `parcel_key` links back to the parcel database when known. */
export interface CrmProperty {
  id: string;
  client_id: string;
  label: string;
  status: PropertyStatus;
  /** "FL:12:PARCELID" — the key used by /api/property, when sourced from search. */
  parcel_key: string | null;
  address: string | null;
  city: string | null;
  postal_code: string | null;
  county: string | null;
  state: string | null;
  acres: number | null;
  purchase_price_cents: number | null;
  /** Title, recording, survey. Adds to LAND basis, so it is not depreciable. */
  closing_costs_cents: number | null;
  /**
   * Site prep attached to the land rather than to one unit — access, well,
   * septic, clearing, utility runs. Depreciable (typically as 15-year land
   * improvements), unlike the land underneath it.
   */
  improvements_cents: number | null;
  purchase_date: string | null;
  assessed_value_cents: number | null;
  annual_property_tax_cents: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * Land BTB owns. The client never appears here — that is the point.
 *
 * A park is bought, developed into pads, and then either carries a client's home
 * or one BTB built for its own book. Its cost basis is BTB's, not a client's,
 * and land is never depreciable in either case.
 */
export interface CrmPark {
  id: string;
  name: string;
  status: ParkStatus;
  /** "FL:12:PARCELID" — links back to the parcel database when sourced there. */
  parcel_key: string | null;
  address: string | null;
  city: string | null;
  postal_code: string | null;
  county: string | null;
  state: string | null;
  acres: number | null;
  purchase_price_cents: number | null;
  /** Title, recording, survey. Adds to LAND basis, so it is not depreciable. */
  closing_costs_cents: number | null;
  /**
   * Site prep attached to the land rather than to one pad — access roads, well,
   * septic, clearing, utility trunk runs. Depreciable (typically as 15-year land
   * improvements), unlike the land underneath it.
   */
  improvements_cents: number | null;
  purchase_date: string | null;
  assessed_value_cents: number | null;
  annual_property_tax_cents: number | null;
  /**
   * How many pads the site is expected to hold once built out. Planning figure
   * only — actual capacity is the count of rows in crm_pads, and the two are
   * shown side by side so a park that has not been built out is visible.
   */
  planned_pad_count: number | null;
  /** A listing (typically Zillow) for land under consideration. */
  listing_url: string | null;
  asking_price_cents: number | null;
  /**
   * What the model says about the AREA — tourism, demand, seasonality.
   * Prose only. Every number on this record is still computed in code.
   */
  area_analysis: string | null;
  area_analysis_at: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** A remark on a piece of land under consideration. */
export interface CrmParkComment {
  id: string;
  park_id: string;
  author_email: string;
  body: string;
  created_at: string;
  updated_at: string;
}

/**
 * One numbered site within a park.
 *
 * This is the unit of capacity and the answer to "how much of our land is this
 * client on": the pad's square footage against the park's acreage.
 */
export interface CrmPad {
  id: string;
  park_id: string;
  /** "A-12". Unique within a park. */
  label: string;
  status: PadStatus;
  /** The client's footprint. */
  pad_sqft: number | null;
  /** Pad-specific development: the slab, the hookups, the skirting. */
  site_work_cents: number | null;
  has_water: boolean | null;
  has_sewer: boolean | null;
  has_power: boolean | null;
  /** What a night on this pad is expected to fetch. Drives the revenue model. */
  nightly_rate_cents: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** A tiny home. Optionally sited on one of the client's land holdings. */
export interface CrmUnit {
  id: string;
  /**
   * NULL means BTB owns this home and rents it on its own book, rather than a
   * client owning it. The dashboard splits the two on exactly this.
   */
  client_id: string | null;
  /** Legacy: a client's own land. See the note on PROPERTY_STATUSES. */
  property_id: string | null;
  /** The pad in a BTB park this home actually stands on. */
  pad_id: string | null;
  /**
   * Bought prefab or built on site. Drives the cost comparison, and is a real
   * tax question too: the memorandum's position rests on the home being
   * transportable personal property with a VIN, which a site-built structure
   * may not be.
   */
  build_method: BuildMethod | null;
  label: string;
  status: UnitStatus;
  unit_use: UnitUse;
  manufacturer: string | null;
  model: string | null;
  serial_number: string | null;
  sqft: number | null;
  bedrooms: number | null;

  purchase_price_cents: number | null;
  site_work_cents: number | null;
  soft_costs_cents: number | null;
  delivered_on: string | null;
  /** Depreciation starts here, not at purchase — an unplaced unit deducts nothing. */
  placed_in_service_on: string | null;
  useful_life_years: number | null;
  bonus_claimed_cents: number | null;
  /** Disposal. Selling early can trigger recapture, so both are worth holding. */
  sold_on: string | null;
  sale_price_cents: number | null;

  monthly_rent_cents: number | null;
  management_company: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmTransaction {
  id: string;
  client_id: string | null;
  property_id: string | null;
  unit_id: string | null;
  kind: TxKind;
  category: TxCategory;
  description: string;
  amount_cents: number;
  occurred_on: string;
  status: TxStatus;
  invoice_number: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** A parcel shortlisted for a client from the in-card land search. */
export interface CrmSavedParcel {
  id: string;
  client_id: string;
  parcel_key: string;
  status: SavedParcelStatus;
  one_line: string | null;
  owner_name: string | null;
  state: string | null;
  county: string | null;
  acres: number | null;
  assessed_value_cents: number | null;
  land_value_cents: number | null;
  /** Cached AI fit read, so re-opening the list doesn't re-bill the model. */
  fit_json: string | null;
  notes: string | null;
  saved_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmActivity {
  id: string;
  entity_type: string;
  entity_id: string | null;
  client_id: string | null;
  verb: string;
  summary: string;
  actor_email: string | null;
  created_at: string;
}

export interface CrmConversation {
  id: string;
  scope_type: AiScope;
  scope_id: string | null;
  title: string;
  created_at: string;
  updated_at: string;
}

export interface CrmMessage {
  id: string;
  conversation_id: string;
  role: "system" | "user" | "assistant";
  content: string;
  created_at: string;
}

/* -------------------------------------------------------------------------- */
/* Labels — the human-readable name for every enum value                       */
/* -------------------------------------------------------------------------- */

export const LABELS = {
  clientStatus: {
    prospect: "Prospect",
    qualified: "Qualified",
    proposal_sent: "Proposal sent",
    contracted: "Contracted",
    owner: "Owner",
    dormant: "Dormant",
    lost: "Lost",
  } satisfies Record<ClientStatus, string>,
  health: {
    green: "On track",
    amber: "Needs attention",
    red: "At risk",
  } satisfies Record<Health, string>,
  entityType: {
    individual: "Individual",
    joint: "Joint / married filing jointly",
    llc: "LLC",
    s_corp: "S-corp",
    c_corp: "C-corp",
    partnership: "Partnership",
    trust: "Trust",
  } satisfies Record<EntityType, string>,
  source: {
    referral: "Referral",
    inbound: "Inbound",
    outbound: "Outbound",
    event: "Event",
    cpa_referral: "CPA referral",
    advisor: "Wealth advisor",
    partner: "Partner",
    other: "Other",
  } satisfies Record<LeadSource, string>,
  contactRole: {
    principal: "Principal",
    spouse: "Spouse",
    cpa: "CPA",
    attorney: "Attorney",
    wealth_advisor: "Wealth advisor",
    assistant: "Assistant",
    other: "Other",
  } satisfies Record<ContactRole, string>,
  proposalStatus: {
    draft: "Draft",
    sent: "Sent",
    accepted: "Accepted",
    declined: "Declined",
    expired: "Expired",
  } satisfies Record<ProposalStatus, string>,
  contractType: {
    equipment_purchase: "Equipment purchase",
    equipment_finance: "Equipment finance (note)",
    management: "Management and revenue share",
    unit_purchase: "Tiny home purchase",
    land_purchase: "Land purchase",
    investment: "Investment agreement",
    lease: "Lease",
    joint_venture: "Joint venture",
  } satisfies Record<ContractType, string>,
  contractStatus: {
    draft: "Draft",
    out_for_signature: "Out for signature",
    signed: "Signed",
    active: "Active",
    completed: "Completed",
    terminated: "Terminated",
  } satisfies Record<ContractStatus, string>,
  propertyStatus: {
    prospect: "Prospect",
    under_contract: "Under contract",
    owned: "Owned",
    listed: "Listed",
    sold: "Sold",
  } satisfies Record<PropertyStatus, string>,
  parkStatus: {
    prospect: "Prospect",
    under_contract: "Under contract",
    owned: "Owned",
    developing: "Developing",
    operating: "Operating",
    sold: "Sold",
  } satisfies Record<ParkStatus, string>,
  padStatus: {
    planned: "Planned",
    building: "Building",
    available: "Available",
    reserved: "Reserved",
    occupied: "Occupied",
    out_of_service: "Out of service",
  } satisfies Record<PadStatus, string>,
  buildMethod: {
    prefab: "Prefab",
    site_built: "Built on site",
  } satisfies Record<BuildMethod, string>,
  unitStatus: {
    planned: "Planned",
    ordered: "Ordered",
    in_production: "In production",
    delivered: "Delivered",
    installed: "Installed",
    in_service: "In service",
    sold: "Sold",
    retired: "Retired",
  } satisfies Record<UnitStatus, string>,
  unitUse: {
    transient_rental: "Transient rental (under 30 days)",
    long_term_rental: "Long-term rental",
    farm_ag: "Farm / agricultural",
    commercial: "Commercial",
    personal: "Personal use",
  } satisfies Record<UnitUse, string>,
  txKind: { income: "Income", expense: "Expense" } satisfies Record<TxKind, string>,
  txCategory: {
    investment: "Client investment",
    deposit: "Deposit",
    land_purchase: "Land purchase",
    unit_purchase: "Unit purchase",
    site_work: "Site work",
    permits: "Permits",
    transport: "Transport & set",
    closing_costs: "Closing costs",
    rent: "Rental income",
    management_fee: "Management fee",
    insurance: "Insurance",
    property_tax: "Property tax",
    maintenance: "Maintenance",
    utilities: "Utilities",
    professional_fees: "Professional fees",
    distribution: "Distribution to client",
    other: "Other",
  } satisfies Record<TxCategory, string>,
  txStatus: {
    draft: "Draft",
    invoiced: "Invoiced",
    paid: "Paid",
    overdue: "Overdue",
    void: "Void",
  } satisfies Record<TxStatus, string>,
  savedParcelStatus: {
    shortlisted: "Shortlisted",
    owner_contacted: "Owner contacted",
    offer_made: "Offer made",
    under_contract: "Under contract",
    acquired: "Acquired",
    rejected: "Rejected",
  } satisfies Record<SavedParcelStatus, string>,
  todoStatus: {
    todo: "To do",
    doing: "In progress",
    done: "Done",
  } satisfies Record<TodoStatus, string>,
} as const;
