// Row shapes and enums for the tiny-home CRM.
//
// Conventions carried through the whole CRM (deviating from them causes real
// bugs, so they are listed once here):
//
//   * ids are TEXT uuids generated by the app (`newId()` in ./db)
//   * money is INTEGER cents, never floats and never dollars — `fmtMoney` in
//     ./format is the only place that divides by 100
//   * rates are basis points (3700 = 37.00%), so no float drift in the DB
//   * timestamps are ISO-8601 TEXT in UTC; plain dates are 'YYYY-MM-DD' TEXT
//   * every enum below mirrors a SQL CHECK constraint in ./schema — adding a
//     value means editing BOTH plus the label map at the bottom of this file

/* -------------------------------------------------------------------------- */
/* Enums — mirrored by CHECK constraints in ./schema.ts                        */
/* -------------------------------------------------------------------------- */

export const CLIENT_STATUSES = [
  "prospect",
  "qualified",
  "proposal_sent",
  "contracted",
  "owner",
  "dormant",
  "lost",
] as const;
export type ClientStatus = (typeof CLIENT_STATUSES)[number];

export const HEALTHS = ["green", "amber", "red"] as const;
export type Health = (typeof HEALTHS)[number];

export const ENTITY_TYPES = [
  "individual",
  "joint",
  "llc",
  "s_corp",
  "c_corp",
  "partnership",
  "trust",
] as const;
export type EntityType = (typeof ENTITY_TYPES)[number];

export const LEAD_SOURCES = [
  "referral",
  "inbound",
  "outbound",
  "event",
  "cpa_referral",
  "advisor",
  "partner",
  "other",
] as const;
export type LeadSource = (typeof LEAD_SOURCES)[number];

export const CONTACT_ROLES = [
  "principal",
  "spouse",
  "cpa",
  "attorney",
  "wealth_advisor",
  "assistant",
  "other",
] as const;
export type ContactRole = (typeof CONTACT_ROLES)[number];

export const PROPOSAL_STATUSES = ["draft", "sent", "accepted", "declined", "expired"] as const;
export type ProposalStatus = (typeof PROPOSAL_STATUSES)[number];

export const CONTRACT_TYPES = [
  "unit_purchase",
  "land_purchase",
  "investment",
  "lease",
  "management",
  "joint_venture",
] as const;
export type ContractType = (typeof CONTRACT_TYPES)[number];

export const CONTRACT_STATUSES = [
  "draft",
  "out_for_signature",
  "signed",
  "active",
  "completed",
  "terminated",
] as const;
export type ContractStatus = (typeof CONTRACT_STATUSES)[number];

/** Land parcels the client owns or is pursuing. */
export const PROPERTY_STATUSES = [
  "prospect",
  "under_contract",
  "owned",
  "listed",
  "sold",
] as const;
export type PropertyStatus = (typeof PROPERTY_STATUSES)[number];

/** A tiny home, from order through disposal. */
export const UNIT_STATUSES = [
  "planned",
  "ordered",
  "in_production",
  "delivered",
  "installed",
  "in_service",
  "sold",
  "retired",
] as const;
export type UnitStatus = (typeof UNIT_STATUSES)[number];

/**
 * How the unit is used. This is the single most consequential field for the tax
 * case: only business/rental use supports a depreciation deduction, so
 * `personal` zeroes the write-off in ./economics rather than quietly inflating it.
 */
export const UNIT_USES = ["long_term_rental", "short_term_rental", "farm_ag", "commercial", "personal"] as const;
export type UnitUse = (typeof UNIT_USES)[number];

export const TX_KINDS = ["income", "expense"] as const;
export type TxKind = (typeof TX_KINDS)[number];

export const TX_CATEGORIES = [
  "investment",
  "deposit",
  "land_purchase",
  "unit_purchase",
  "site_work",
  "permits",
  "transport",
  "closing_costs",
  "rent",
  "management_fee",
  "insurance",
  "property_tax",
  "maintenance",
  "utilities",
  "professional_fees",
  "distribution",
  "other",
] as const;
export type TxCategory = (typeof TX_CATEGORIES)[number];

export const TX_STATUSES = ["draft", "invoiced", "paid", "overdue", "void"] as const;
export type TxStatus = (typeof TX_STATUSES)[number];

/** Where a shortlisted parcel stands for this client. */
export const SAVED_PARCEL_STATUSES = [
  "shortlisted",
  "owner_contacted",
  "offer_made",
  "under_contract",
  "acquired",
  "rejected",
] as const;
export type SavedParcelStatus = (typeof SAVED_PARCEL_STATUSES)[number];

export const AI_SCOPES = ["global", "client"] as const;
export type AiScope = (typeof AI_SCOPES)[number];

/* -------------------------------------------------------------------------- */
/* Rows                                                                        */
/* -------------------------------------------------------------------------- */

export interface CrmClient {
  id: string;
  name: string;
  legal_name: string | null;
  status: ClientStatus;
  health: Health;
  source: LeadSource;
  entity_type: EntityType;

  email: string | null;
  phone: string | null;
  city: string | null;
  state: string | null;

  /** Tax profile — drives every figure in ./economics. */
  tax_state: string | null;
  /** Marginal federal+state rate in basis points (3700 = 37%). */
  marginal_rate_bps: number | null;
  est_annual_income_cents: number | null;
  target_writeoff_cents: number | null;
  investment_capacity_cents: number | null;
  cpa_name: string | null;
  cpa_email: string | null;

  /** Land criteria — pre-fills the per-client parcel search. */
  target_state: string | null;
  target_county: string | null;
  target_min_acres: number | null;
  target_max_acres: number | null;
  target_max_price_cents: number | null;

  owner_email: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmContact {
  id: string;
  client_id: string;
  name: string;
  role: ContactRole;
  title: string | null;
  email: string | null;
  phone: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmProposal {
  id: string;
  client_id: string;
  title: string;
  status: ProposalStatus;

  /** Frozen inputs — what was quoted, kept verbatim so the doc never drifts. */
  unit_count: number;
  unit_cost_cents: number;
  site_work_cents: number;
  soft_costs_cents: number;
  land_cost_cents: number;
  marginal_rate_bps: number;
  bonus_rate_bps: number;
  useful_life_years: number;
  monthly_rent_cents: number;
  occupancy_bps: number;
  opex_bps: number;

  /** Frozen outputs — computed in code, never by the model. */
  total_investment_cents: number;
  depreciable_basis_cents: number;
  year_one_deduction_cents: number;
  year_one_tax_savings_cents: number;
  net_year_one_outlay_cents: number;
  annual_noi_cents: number;
  cash_on_cash_bps: number | null;
  payback_years: number | null;

  body_md: string;
  valid_until: string | null;
  created_by: string | null;
  sent_at: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmContract {
  id: string;
  client_id: string;
  proposal_id: string | null;
  title: string;
  type: ContractType;
  status: ContractStatus;
  value_cents: number;
  counterparty: string | null;
  document_url: string | null;
  effective_date: string | null;
  end_date: string | null;
  signed_at: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** A land holding. `parcel_key` links back to the parcel database when known. */
export interface CrmProperty {
  id: string;
  client_id: string;
  label: string;
  status: PropertyStatus;
  /** "FL:12:PARCELID" — the key used by /api/property, when sourced from search. */
  parcel_key: string | null;
  address: string | null;
  city: string | null;
  postal_code: string | null;
  county: string | null;
  state: string | null;
  acres: number | null;
  purchase_price_cents: number | null;
  /** Title, recording, survey. Adds to LAND basis, so it is not depreciable. */
  closing_costs_cents: number | null;
  /**
   * Site prep attached to the land rather than to one unit — access, well,
   * septic, clearing, utility runs. Depreciable (typically as 15-year land
   * improvements), unlike the land underneath it.
   */
  improvements_cents: number | null;
  purchase_date: string | null;
  assessed_value_cents: number | null;
  annual_property_tax_cents: number | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** A tiny home. Optionally sited on one of the client's land holdings. */
export interface CrmUnit {
  id: string;
  client_id: string;
  property_id: string | null;
  label: string;
  status: UnitStatus;
  unit_use: UnitUse;
  manufacturer: string | null;
  model: string | null;
  serial_number: string | null;
  sqft: number | null;
  bedrooms: number | null;

  purchase_price_cents: number | null;
  site_work_cents: number | null;
  soft_costs_cents: number | null;
  delivered_on: string | null;
  /** Depreciation starts here, not at purchase — an unplaced unit deducts nothing. */
  placed_in_service_on: string | null;
  useful_life_years: number | null;
  bonus_claimed_cents: number | null;
  /** Disposal. Selling early can trigger recapture, so both are worth holding. */
  sold_on: string | null;
  sale_price_cents: number | null;

  monthly_rent_cents: number | null;
  management_company: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmTransaction {
  id: string;
  client_id: string | null;
  property_id: string | null;
  unit_id: string | null;
  kind: TxKind;
  category: TxCategory;
  description: string;
  amount_cents: number;
  occurred_on: string;
  status: TxStatus;
  invoice_number: string | null;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

/** A parcel shortlisted for a client from the in-card land search. */
export interface CrmSavedParcel {
  id: string;
  client_id: string;
  parcel_key: string;
  status: SavedParcelStatus;
  one_line: string | null;
  owner_name: string | null;
  state: string | null;
  county: string | null;
  acres: number | null;
  assessed_value_cents: number | null;
  land_value_cents: number | null;
  /** Cached AI fit read, so re-opening the list doesn't re-bill the model. */
  fit_json: string | null;
  notes: string | null;
  saved_by: string | null;
  created_at: string;
  updated_at: string;
}

export interface CrmActivity {
  id: string;
  entity_type: string;
  entity_id: string | null;
  client_id: string | null;
  verb: string;
  summary: string;
  actor_email: string | null;
  created_at: string;
}

export interface CrmConversation {
  id: string;
  scope_type: AiScope;
  scope_id: string | null;
  title: string;
  created_at: string;
  updated_at: string;
}

export interface CrmMessage {
  id: string;
  conversation_id: string;
  role: "system" | "user" | "assistant";
  content: string;
  created_at: string;
}

/* -------------------------------------------------------------------------- */
/* Labels — the human-readable name for every enum value                       */
/* -------------------------------------------------------------------------- */

export const LABELS = {
  clientStatus: {
    prospect: "Prospect",
    qualified: "Qualified",
    proposal_sent: "Proposal sent",
    contracted: "Contracted",
    owner: "Owner",
    dormant: "Dormant",
    lost: "Lost",
  } satisfies Record<ClientStatus, string>,
  health: {
    green: "On track",
    amber: "Needs attention",
    red: "At risk",
  } satisfies Record<Health, string>,
  entityType: {
    individual: "Individual",
    joint: "Joint / married filing jointly",
    llc: "LLC",
    s_corp: "S-corp",
    c_corp: "C-corp",
    partnership: "Partnership",
    trust: "Trust",
  } satisfies Record<EntityType, string>,
  source: {
    referral: "Referral",
    inbound: "Inbound",
    outbound: "Outbound",
    event: "Event",
    cpa_referral: "CPA referral",
    advisor: "Wealth advisor",
    partner: "Partner",
    other: "Other",
  } satisfies Record<LeadSource, string>,
  contactRole: {
    principal: "Principal",
    spouse: "Spouse",
    cpa: "CPA",
    attorney: "Attorney",
    wealth_advisor: "Wealth advisor",
    assistant: "Assistant",
    other: "Other",
  } satisfies Record<ContactRole, string>,
  proposalStatus: {
    draft: "Draft",
    sent: "Sent",
    accepted: "Accepted",
    declined: "Declined",
    expired: "Expired",
  } satisfies Record<ProposalStatus, string>,
  contractType: {
    unit_purchase: "Tiny home purchase",
    land_purchase: "Land purchase",
    investment: "Investment agreement",
    lease: "Lease",
    management: "Management agreement",
    joint_venture: "Joint venture",
  } satisfies Record<ContractType, string>,
  contractStatus: {
    draft: "Draft",
    out_for_signature: "Out for signature",
    signed: "Signed",
    active: "Active",
    completed: "Completed",
    terminated: "Terminated",
  } satisfies Record<ContractStatus, string>,
  propertyStatus: {
    prospect: "Prospect",
    under_contract: "Under contract",
    owned: "Owned",
    listed: "Listed",
    sold: "Sold",
  } satisfies Record<PropertyStatus, string>,
  unitStatus: {
    planned: "Planned",
    ordered: "Ordered",
    in_production: "In production",
    delivered: "Delivered",
    installed: "Installed",
    in_service: "In service",
    sold: "Sold",
    retired: "Retired",
  } satisfies Record<UnitStatus, string>,
  unitUse: {
    long_term_rental: "Long-term rental",
    short_term_rental: "Short-term rental",
    farm_ag: "Farm / agricultural",
    commercial: "Commercial",
    personal: "Personal use",
  } satisfies Record<UnitUse, string>,
  txKind: { income: "Income", expense: "Expense" } satisfies Record<TxKind, string>,
  txCategory: {
    investment: "Client investment",
    deposit: "Deposit",
    land_purchase: "Land purchase",
    unit_purchase: "Unit purchase",
    site_work: "Site work",
    permits: "Permits",
    transport: "Transport & set",
    closing_costs: "Closing costs",
    rent: "Rental income",
    management_fee: "Management fee",
    insurance: "Insurance",
    property_tax: "Property tax",
    maintenance: "Maintenance",
    utilities: "Utilities",
    professional_fees: "Professional fees",
    distribution: "Distribution to client",
    other: "Other",
  } satisfies Record<TxCategory, string>,
  txStatus: {
    draft: "Draft",
    invoiced: "Invoiced",
    paid: "Paid",
    overdue: "Overdue",
    void: "Void",
  } satisfies Record<TxStatus, string>,
  savedParcelStatus: {
    shortlisted: "Shortlisted",
    owner_contacted: "Owner contacted",
    offer_made: "Offer made",
    under_contract: "Under contract",
    acquired: "Acquired",
    rejected: "Rejected",
  } satisfies Record<SavedParcelStatus, string>,
} as const;
