/**
 * Image attachments — the SERVER half, and the only file in the app that knows
 * S3 exists.
 *
 * Everything else deals in `crm_attachments` rows and in the id-addressed route
 * that serves them. That is the same containment `recall.ts` gives the meeting
 * vendor, and for the same reason: swapping the store, or adding a second one,
 * should be this file and nothing else.
 *
 * NEVER import this from a client component. It pulls in the AWS SDK and reads
 * the environment; `./attachments.ts` is the pure half the browser is allowed.
 *
 * **The bytes are proxied, never linked.** `GET /api/crm/attachments/[id]` reads
 * the object through this module and streams it out behind the ordinary session
 * check. The alternative — handing the browser a presigned URL — was rejected
 * twice over: a presigned link embedded in a comment expires and rots the
 * history, and one issued to a browser is a bearer token for that object which
 * outlives the session that earned it. These images sit next to named taxpayers.
 * The bucket has no public access and no bucket policy, and nothing about that
 * should have to be re-argued when someone wants to save a network hop.
 *
 * **Config fails closed.** With no bucket configured, uploading throws with the
 * parameter to set. It does not fall back to a default bucket name, because a
 * plausible-but-wrong bucket is how uploads end up somewhere nobody is looking.
 */

import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { CrmError, newId, nowIso, query, queryOne } from "./db";
import {
  ALLOWED_IMAGE_TYPES,
  MAX_ATTACHMENT_BYTES,
  extensionFor,
  fmtBytes,
  isAllowedImageType,
} from "./attachments";

export interface CrmAttachment {
  id: string;
  storage_key: string;
  content_type: string;
  byte_size: number;
  file_name: string | null;
  uploaded_by: string | null;
  created_at: string;
}

let s3: S3Client | null = null;

function client(): S3Client {
  // The region comes from the environment the container already has — the
  // instance role's credentials are resolved by the SDK's default chain from
  // IMDS, so there is no key here and there must never be one.
  if (!s3) s3 = new S3Client({ region: process.env.AWS_REGION || "us-east-1" });
  return s3;
}

export function uploadsBucket(): string {
  const bucket = process.env.CRM_UPLOADS_BUCKET;
  if (!bucket) {
    throw new CrmError(
      "Uploads are not configured. Set /btb-crm/CRM_UPLOADS_BUCKET and redeploy.",
      503,
    );
  }
  return bucket;
}

export function areUploadsConfigured(): boolean {
  return Boolean(process.env.CRM_UPLOADS_BUCKET);
}

/**
 * The object key.
 *
 * Under `uploads/` because the instance role is scoped to exactly that prefix —
 * a key outside it is a 403 at write time, which is the intended floor rather
 * than an inconvenience. Dated so the bucket stays navigable by hand, and named
 * by the row id so an object and its row can always be matched up. The id is
 * generated by us and is not user input, so there is nothing here to escape.
 */
function storageKey(id: string, contentType: string): string {
  const at = new Date();
  const month = `${at.getUTCFullYear()}/${String(at.getUTCMonth() + 1).padStart(2, "0")}`;
  const ext = isAllowedImageType(contentType) ? extensionFor(contentType) : "bin";
  return `uploads/${month}/${id}.${ext}`;
}

/**
 * Store an image and record it.
 *
 * Validation is here rather than only in the route, because this is the choke
 * point every caller passes through — and the browser's own pre-check is a
 * courtesy, not a control. It is checked against the DECLARED type and the
 * ACTUAL byte length; a lying `Content-Type` on a 40 MB file would otherwise
 * be a way to fill the bucket.
 */
export async function createAttachment(args: {
  bytes: Buffer;
  contentType: string;
  fileName: string | null;
  uploadedBy: string;
}): Promise<CrmAttachment> {
  if (!isAllowedImageType(args.contentType)) {
    throw new CrmError(
      `That file type isn't supported. Images only: ${ALLOWED_IMAGE_TYPES.join(", ")}.`,
      400,
    );
  }
  if (args.bytes.byteLength === 0) throw new CrmError("That file is empty.", 400);
  if (args.bytes.byteLength > MAX_ATTACHMENT_BYTES) {
    throw new CrmError(
      `That image is ${fmtBytes(args.bytes.byteLength)}. The limit is ${fmtBytes(MAX_ATTACHMENT_BYTES)}.`,
      400,
    );
  }

  const bucket = uploadsBucket();
  const id = newId();
  const key = storageKey(id, args.contentType);

  // S3 FIRST, then the row. The other order can leave a row pointing at an
  // object that was never written — an image that renders as a broken box
  // forever. This order can leave an orphaned object instead, which costs a
  // fraction of a cent and is invisible. See the note on deletion below.
  await client().send(
    new PutObjectCommand({
      Bucket: bucket,
      Key: key,
      Body: args.bytes,
      ContentType: args.contentType,
      // Belt and braces against a future bucket policy change: an object that
      // is never public cannot be made public by loosening the bucket.
      ServerSideEncryption: "AES256",
    }),
  );

  const rows = await query<CrmAttachment>(
    `INSERT INTO crm_attachments (id, storage_key, content_type, byte_size, file_name, uploaded_by, created_at, updated_at)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
     RETURNING id, storage_key, content_type, byte_size, file_name, uploaded_by, created_at`,
    [id, key, args.contentType, args.bytes.byteLength, args.fileName, args.uploadedBy, nowIso()],
  );
  return rows[0];
}

export async function getAttachment(id: string): Promise<CrmAttachment | null> {
  return queryOne<CrmAttachment>(
    `SELECT id, storage_key, content_type, byte_size, file_name, uploaded_by, created_at
     FROM crm_attachments WHERE id = $1`,
    [id],
  );
}

/**
 * The bytes.
 *
 * Buffered rather than streamed straight through. These are capped at 5 MB and
 * the alternative is handing a web stream from the SDK to the Response
 * constructor, where a mid-transfer failure has no way to become a status code
 * — the headers have already gone. At this size the whole object is one read.
 */
export async function readAttachmentBytes(row: CrmAttachment): Promise<Buffer> {
  const out = await client().send(
    new GetObjectCommand({ Bucket: uploadsBucket(), Key: row.storage_key }),
  );
  if (!out.Body) throw new CrmError("That image is missing from storage.", 404);
  return Buffer.from(await out.Body.transformToByteArray());
}

/** What the model is sent. See the vision note in ./advisor.ts. */
export async function attachmentDataUrl(row: CrmAttachment): Promise<string> {
  const bytes = await readAttachmentBytes(row);
  return `data:${row.content_type};base64,${bytes.toString("base64")}`;
}

/**
 * Remove one.
 *
 * NOT called by anything today, and that is a decision rather than an omission.
 * An image lives in the body of a comment or a description as Markdown, so
 * "delete the comment" would have to parse its text to know what to collect,
 * and it would be wrong the moment the same image had been pasted into a second
 * card — which is exactly what people do. Orphans cost storage and nothing
 * else. A sweep that deletes attachments no live text references is the right
 * shape for that job, and it is not this function.
 */
export async function deleteAttachment(id: string): Promise<void> {
  const row = await getAttachment(id);
  if (!row) return;
  await client().send(
    new DeleteObjectCommand({ Bucket: uploadsBucket(), Key: row.storage_key }),
  );
  await query("DELETE FROM crm_attachments WHERE id = $1", [id]);
}

/* -------------------------------------------------------------------------- */
/* Documents                                                                   */
/*                                                                             */
/* The learn-from-a-document feature stores its files here too, because this is */
/* still the only file that knows S3 exists and there is no reason for a second */
/* bucket — the blast radius is identical and the role is already scoped to the */
/* `uploads/` prefix. Everything ABOVE this line is images and everything below */
/* is documents; the row types and the tables stay apart. See ./knowledge.ts.   */
/* -------------------------------------------------------------------------- */

/**
 * Where a document's bytes go.
 *
 * Under `uploads/documents/`, which is inside the prefix the instance role is
 * scoped to — a key outside `uploads/` is a 403 at write time. The extra
 * segment is not access control, it is so that someone looking in the bucket by
 * hand can tell a pasted screenshot from a client's memorandum.
 */
function documentStorageKey(id: string, extension: string): string {
  const at = new Date();
  const month = `${at.getUTCFullYear()}/${String(at.getUTCMonth() + 1).padStart(2, "0")}`;
  return `uploads/documents/${month}/${id}.${extension}`;
}

/** Store a document's bytes. The row is the caller's job — see ./knowledge.ts. */
export async function putDocumentObject(args: {
  id: string;
  bytes: Buffer;
  contentType: string;
  extension: string;
}): Promise<string> {
  const key = documentStorageKey(args.id, args.extension);
  await client().send(
    new PutObjectCommand({
      Bucket: uploadsBucket(),
      Key: key,
      Body: args.bytes,
      ContentType: args.contentType,
      ServerSideEncryption: "AES256",
    }),
  );
  return key;
}

/**
 * A document's bytes, for the download route.
 *
 * Buffered rather than streamed, for the reason `readAttachmentBytes` gives: a
 * mid-transfer failure on a streamed body has no way to become a status code.
 * These are capped at 20 MB, which is four times an image and still one read.
 */
export async function readDocumentBytes(storageKey: string): Promise<Buffer> {
  const out = await client().send(
    new GetObjectCommand({ Bucket: uploadsBucket(), Key: storageKey }),
  );
  if (!out.Body) throw new CrmError("That document is missing from storage.", 404);
  return Buffer.from(await out.Body.transformToByteArray());
}

/**
 * Remove a document's bytes.
 *
 * Unlike `deleteAttachment` this one IS called: a document has a single owning
 * row and a Delete button in the library, so there is no ambiguity about who
 * else is pointing at it. The object goes first and the row second — the
 * opposite order to the write, so neither order can leave a row promising bytes
 * that are not there.
 */
export async function deleteDocumentObject(storageKey: string): Promise<void> {
  await client().send(new DeleteObjectCommand({ Bucket: uploadsBucket(), Key: storageKey }));
}
